os: linux
dist: bionic
language: python
python:
- "3.8"

# prevent branch builds that aren't PRs
branches:
  only:
  - master

env:
  global:
  - BUILD_NAME=FiscalShock

after_failure:
- bash ./ci/discord_hook.sh failure ${WEBHOOK_URL}

addons:
  apt:
    packages:
    - doxygen

cache:
  directories:
  - .git/lfs
  - rls_win64
  - rls_linux64
  - rls_mac

git:
  depth: 25  # warning: tags more than this many commits ago will be lost!
  lfs_skip_smudge: true

services:
- docker

stages:
- test
- build
- docs
- deploy

################################################################################

jobs:
  include:
  - stage: test
    name: "Tests"
    if: type == pull_request
    script:
    - source ./ci/travis_prepare_workspace.sh
    - bash ./ci/travis_run_tests.sh
    - echo Testing Linux build
    - bash ./ci/docker_build.sh
    env: IMAGE_NAME=gableroux/unity3d:2019.3.0f6 BUILD_TARGET=StandaloneLinux64 OPTS=-force-glcore BUILD_DIR=FiscalShock-linux64

################################################################################

  - stage: docs
    name: "Doxygen"
    script: bash ./ci/generate_docs.sh
    if: type != pull_request
    deploy:
      provider: pages:git
      token: $GITHUB_TOKEN
      edge: true
      commit_message: Update Doxygen %{git_sha}
      verbose: true
      project_name: Fiscal Shock
      local_dir: docs/html
      skip_cleanup: true
      name: "Deploy Moar RAM"
      email: "52723879+travis-pantry-raid@users.noreply.github.com"
      on:
        branch: master

################################################################################

  - stage: build
  ############
  # Linux 64
  ############
    script:
    - export IMAGE_NAME=gableroux/unity3d:2019.3.0f6; export BUILD_TARGET=StandaloneLinux64; export OPTS=-force-glcore; export BUILD_DIR=FiscalShock-linux64
    - source ./ci/travis_prepare_workspace.sh
    - bash ./ci/lfs_pull.sh
    - bash ./ci/docker_build.sh
    - bash ./ci/package_build.sh linux64
    name: "Build and cache Linux64 (OpenGL)"
    if: type != pull_request

  ############
  # Windows 64
  ############
  - script:
    - export IMAGE_NAME=gableroux/unity3d:2019.3.0f6-windows; export BUILD_TARGET=StandaloneWindows64; export OPTS=-force-glcore; export BUILD_DIR=FiscalShock-win64
    - source ./ci/travis_prepare_workspace.sh
    - bash ./ci/lfs_pull.sh
    - bash ./ci/docker_build.sh
    - bash ./ci/package_build.sh win64
    name: "Build and cache Windows64 (OpenGL)"
    if: type != pull_request

  ############
  # mac
  ############
  - script:
    - export BUILD_TARGET=StandaloneOSX; export IMAGE_NAME=gableroux/unity3d:2019.3.0f6-mac; export OPTS=-force-glcore; export BUILD_DIR=FiscalShock-mac
    - source ./ci/travis_prepare_workspace.sh
    - bash ./ci/lfs_pull.sh
    - bash ./ci/docker_build.sh
    - bash ./ci/package_build.sh mac
    name: "Build and cache macOS (OpenGL)"
    if: type != pull_request

################################################################################

  - stage: deploy
    script:
    - ls -la rls*
    - source ./ci/verify_package.sh linux64
    - source ./ci/verify_package.sh win64
    - source ./ci/verify_package.sh mac
    - bash ./ci/travis_set_tag.sh
    name: Publish release to GitHub
    if: type != pull_request
    deploy:
      provider: releases
      api_key: $GITHUB_TOKEN
      skip_cleanup: true
      name: "Fiscal Shock auto release ${git_sha}"
      body: "These releases were built automatically for OpenGL from commit %{git_sha}."
      overwrite: true
      prerelease: true
      file:
      - rls_linux64/FiscalShock-linux64.tar.gz
      - rls_win64/FiscalShock-win64.zip
      - rls_mac/FiscalShock-mac.tar.gz
