os: linux
dist: bionic
language: python
python:
- "3.8"

# prevent branch builds that aren't PRs
branches:
  only:
  - master

env:
  global:
  - BUILD_NAME=FiscalShock
  - IMAGE_NAME=gableroux/unity3d:2019.3.0f6

after_failure:
- bash ./ci/discord_hook.sh failure ${WEBHOOK_URL}

addons:
  apt:
    packages:
    - doxygen

cache:
  directories:
  - .git/lfs

git:
  depth: 25  # warning: tags more than this many commits ago will be lost!
  lfs_skip_smudge: true

services:
- docker

stages:
- test
- build
- docs

################################################################################

jobs:
  include:
  - stage: test
    name: "Tests"
    if: type == pull_request
    script:
    - source ./ci/travis_prepare_workspace.sh
    - bash ./ci/travis_run_tests.sh

  - stage: docs
    name: "Doxygen"
    script: bash ./ci/generate_docs.sh
    if: type != pull_request
    deploy:
      provider: pages:git
      token: $GITHUB_TOKEN
      edge: true
      commit_message: Update Doxygen %{git_sha}
      verbose: true
      project_name: Fiscal Shock
      local_dir: docs/html
      skip_cleanup: true
      name: "Deploy Moar RAM"
      email: "52723879+travis-pantry-raid@users.noreply.github.com"
      on:
        branch: master

################################################################################

  - stage: build
    name: "Create new version tag"
    script:
    - bash ./ci/travis_set_tag.sh
    if: type != pull_request
    on:
      branch: master

  ############
  # Linux 64
  ############
  - script:
    - source ./ci/travis_prepare_workspace.sh
    - bash ./ci/docker_build.sh
    - pushd .; cd Builds; tar -czf ../FiscalShock-linux64.tar.gz FiscalShock-linux64
    - popd
    name: "Build and draft Linux64 (OpenGL)"
    #if: type != pull_request  # uncomment to disable building on PRs
    env: IMAGE_NAME=gableroux/unity3d:2019.3.0f6 BUILD_TARGET=StandaloneLinux64 OPTS=-force-glcore BUILD_DIR=FiscalShock-linux64
    deploy:
      provider: releases
      api_key: $GITHUB_TOKEN
      skip_cleanup: true
      file: FiscalShock-linux64.tar.gz
      draft: true
      prerelease: true
      overwrite: true

  # ############
  # # Windows 64
  # ############
  - script:
    - source ./ci/travis_prepare_workspace.sh
    - bash ./ci/docker_build.sh
    - pushd .; cd Builds; zip -r -9 ../FiscalShock-win64.zip FiscalShock-win64
    - popd
    name: "Build and draft Windows64 (OpenGL)"
    env: IMAGE_NAME=gableroux/unity3d:2019.3.0f6-windows BUILD_TARGET=StandaloneWindows64 OPTS=-force-glcore BUILD_DIR=FiscalShock-win64
    if: type != pull_request
    deploy:
      provider: releases
      api_key: $GITHUB_TOKEN
      skip_cleanup: true
      file:
      - FiscalShock-win64.zip
      draft: true
      prerelease: true
      overwrite: true

  ############
  # mac
  ############
  - script:
    - source ./ci/travis_prepare_workspace.sh
    - bash ./ci/docker_build.sh
    - pushd .; cd Builds; tar -czf ../FiscalShock-mac.tar.gz FiscalShock-mac
    - popd
    # Only apply tag on last build
    name: "Build and draft macOS (OpenGL)"
    env: BUILD_TARGET=StandaloneOSX IMAGE_NAME=gableroux/unity3d:2019.3.0f6-mac OPTS=-force-glcore BUILD_DIR=FiscalShock-mac
    if: type != pull_request
    deploy:
      provider: releases
      api_key: $GITHUB_TOKEN
      skip_cleanup: true
      file: FiscalShock-mac.tar.gz
      name: "Fiscal Shock auto release ${git_sha}"
      body: "These releases were built automatically for OpenGL from commit %{git_sha}."
      #draft: true  # uncomment to avoid publishing draft
      overwrite: true
      prerelease: true

################################################################################
